### ISSUE TITLE
Incompatible with latest amaranth version

### ISSUE THREAD

**Issue by fritzbauer** [hansfbaier/adat-usb2-audio-interface#15]
## Issue
2 Months ago many of the "compat" classes were removed from amaranth with this commit: https://github.com/amaranth-lang/amaranth/commit/9d4ffab104a048c7b551d66506761e3397b4ce48
Therefore, the audio interface is failing to build with various places still using the compat parts.
For instance starting with i2c from amlib which is using MultiReg:
https://github.com/amaranth-farm/amlib/blob/main/amlib/io/i2c.py#L12

## Workaround
I am able to build the gateware with these revisions of amaranth and amaranth-soc:
git+https://github.com/amaranth-lang/amaranth.git@597b1b883924d8949061b52270eb55b97a7cfb76
git+https://github.com/amaranth-lang/amaranth-soc.git@87ee8a52d07a2f85b05a04db84644dce48fdfa23

## Fixing
I hope this project is still paused and not abandoned ;) If it is abandoned (along with amaranth-boards, amlib, usb2-highspeed-core) let me know, so I will probably continue working on this in my own forks. Otherwise, I will try to help fixing the references, but might need some help/hints. It would be a shame if this amazing codebase gets so outdated that it cannot be built in the future anymore.
Thank you!

**Comment by hansfbaier** [comment]
Hello, thanks for the update. Since the recent amaranth release mainly removes stuff, I don't really see the necessity to move to a later amaranth release anytime soon.
Hmm the project is not really dead, and sometimes I feel a bit bad about it being so dormant, but I have too many projects going on (a FPGA toolchain and a retro gaming console) that are just eating too much of my time and energy.
One of my plans it to integrate the jt51 core as an (optional) hardware synth into the audio interface, but that also would
need some serious software to go along with it.
Feel free to submit PRs, and the proposed workaround is totally fine with me.

**Comment by hansfbaier** [comment]
BTW, porting the I2C core to normal, non-compat Amaranth, should not be hard at all.
Are we using it in the soundcard design?

**Comment by hansfbaier** [comment]
@fritzbauer If you have pull requests with fixes for me, they are welcome!

**Comment by hansfbaier** [comment]
@fritzbauer OK, I updated the project to use amaranth 0.4.5,
that is the latest one that would work without major changes to amlib.
Now everything works and builds again.
